---
- hosts: all
  remote_user: root
  tasks:
  - name: install the 'Development tools' package group
    yum:
      name: "@Development tools"
      state: present
  - name: ensure a list of packages installed
    yum:
      name: "{{ packages }}"
    vars:
      packages:
      - git
      - nasm
      - autoconf
      - automake
      - texinfo
      - flex
      - bison
      - gcc
      - gcc-c++
      - make
      - glibc-devel
      - zlib-devel
      - xorriso
      - curl-devel
      - byacc
      - libstdc++-static
      - mtools 
      - glibc-devel.x86_64
      - libstdc++-devel.x86_64
      - python3
      - wget
  - name: Cloning Haiku Buildtools
    git:
      repo: 'https://review.haiku-os.org/buildtools'
      dest: /home/buildtools
      version: HEAD
      force: yes
  - name: Cloning Haiku sourcecode
    git:
      repo: 'https://review.haiku-os.org/haiku'
      dest: /home/haiku
      version: HEAD
      force: yes
  - name: Creation of binary target for Haiku
    file:
      path: /home/haiku/generated.x86_64
      state: directory
  - name: creating configuration to build Haiku cross-compiler buildtools
    shell:
      cmd: /home/haiku/configure --build-cross-tools x86_64 /home/buildtools
      chdir: /home/haiku/generated.x86_64/
  - name: Making jam
    make:
      chdir: /home/buildtools/jam/
  - name: Installing jam
    shell:
      cmd: ./jam0 install
      chdir: /home/buildtools/jam/
  