---
- hosts: all
  remote_user: root
  tasks:
  - name: install the 'Development tools' package group
    yum:
      name: "@Development tools"
      state: present
  - name: ensure a list of packages installed
    yum:
      name: "{{ packages }}"
    vars:
      packages:
      - git
      - nasm
      - autoconf
      - automake
      - texinfo
      - flex
      - bison
      - gcc
      - gcc-c++
      - make
      - glibc-devel
      - zlib-devel
      - xorriso
      - curl-devel
      - byacc
      - libstdc++-static
      - mtools 
      - glibc-devel.x86_64
      - libstdc++-devel.x86_64
      - python3
      - wget
  - name: Cloning Haiku Buildtools
    git:
      repo: 'https://review.haiku-os.org/buildtools'
      dest: /home/vagrant/buildtools
      version: HEAD
      force: yes
  - name: Cloning Haiku sourcecode
    git:
      repo: 'https://review.haiku-os.org/haiku'
      dest: /home/vagrant/haiku
      version: HEAD
      force: yes
  - name: Change Ownership of haiku Source Directory
    file:
      path: /home/vagrant/haiku/
      state: directory
      recurse: yes
      owner: vagrant
      group: vagrant
  - name: Change Ownership of haiku Buildtools Directory
    file:
      path: /home/vagrant/buildtools/
      state: directory
      recurse: yes
      owner: vagrant
      group: vagrant
  - name: Creation of binary target for Haiku
    file:
      path: /home/vagrant/generated.x86_64
      state: directory
      owner: vagrant
      group: vagrant
  - name: creating configuration to build Haiku cross-compiler buildtools
    shell:
      cmd: /home/vagrant/haiku/configure --build-cross-tools x86_64 /home/vagrant/buildtools
      chdir: /home/vagrant/generated.x86_64/
  - name: Taking OWnership again on binary target folder
    file:
      path: /home/vagrant/generated.x86_64/
      state: directory
      recurse: yes
      owner: vagrant
      group: vagrant
  - name: Making jam
    make:
      chdir: /home/vagrant/buildtools/jam/
  - name: Installing jam
    shell:
      cmd: ./jam0 install
      chdir: /home/vagrant/buildtools/jam/
  