---
- hosts: all
  remote_user: root
  tasks:
  - name: Installing development tools and dependencies
    ansible.builtin.dnf:
      name:
      - git 
      - nasm 
      - autoconf 
      - automake 
      - texinfo 
      - flex 
      - bison 
      - gcc 
      - gcc-c++ 
      - make 
      - glibc-devel 
      - zlib-devel 
      - libzstd-devel
      - xorriso 
      - curl-devel 
      - byacc 
      - libstdc++-static 
      - glibc-devel.i686 
      - libstdc++-devel.i686 
      - libstdc++-devel 
      - python3
      - libfdt
      state: latest
      enablerepo: devel
  - name: Cloning Haiku Buildtools
    ansible.builtin.git:
      repo: 'https://review.haiku-os.org/buildtools'
      dest: /home/vagrant/buildtools
      version: HEAD
  - name: Cloning Haiku sourcecode
    ansible.builtin.git:
      repo: 'https://review.haiku-os.org/haiku'
      dest: /home/vagrant/haiku
      version: HEAD
      force: yes
  - name: Change Ownership of haiku Source Directory
    file:
      path: /home/vagrant/haiku/
      state: directory
      recurse: yes
      owner: vagrant
      group: vagrant
  - name: Change Ownership of haiku Buildtools Directory
    file:
      path: /home/vagrant/buildtools/
      state: directory
      recurse: yes
      owner: vagrant
      group: vagrant
  - name: Creation of x86-64 binary target for Haiku
    file:
      path: /home/vagrant/generated.x86_64
      state: directory
      owner: vagrant
      group: vagrant
  - name: Creation of ARM binary target for Haiku
    file:
      path: /home/vagrant/generated.arm
      state: directory
      owner: vagrant
      group: vagrant
  - name: creating configuration to build Haiku cross-compiler buildtools for x86-64
    shell:
      cmd: ../haiku/configure --cross-tools-source /home/vagrant/buildtools --build-cross-tools x86_64 
      chdir: /home/vagrant/generated.x86_64/
  - name: Taking Ownership again on binary target x86-64 folder
    file:
      path: /home/vagrant/generated.x86_64/
      state: directory
      recurse: yes
      owner: vagrant
      group: vagrant
  - name: creating configuration to build Haiku cross-compiler buildtools for ARM
    shell:
      cmd: ../haiku/configure --cross-tools-source /home/vagrant/buildtools --build-cross-tools arm 
      chdir: /home/vagrant/generated.arm/
  - name: Taking Ownership again on binary target ARM folder
    file:
      path: /home/vagrant/generated.arm/
      state: directory
      recurse: yes
      owner: vagrant
      group: vagrant
  - name: Making jam
    make:
      chdir: /home/vagrant/buildtools/jam/
  - name: Installing jam
    shell:
      cmd: ./jam0 install
      chdir: /home/vagrant/buildtools/jam/

  